### ISSUE TITLE
Question on re-weighting biased data

### ISSUE THREAD

**Issue by yihengwuKP** [hsidky/dmaps#3]
Hi, in the [README.md](https://github.com/hsidky/dmaps/blob/master/README.md), it's mentioned that the package is able to re-weight the kernel for biased input. I wonder how to use that feature since it's not mentioned in the README. 

I also can't find the "example folder" that's mentioned in the README. The [link](https://sidky.io/blog/diffusion-maps-part-2/) to the blog that's mentioned in other issues is also down. Also, is the reweighting scheme the same as the [umbrella integrated dmap](https://aip.scitation.org/doi/10.1063/1.3574394) paper?

**Comment by hsidky** [comment]
Hi. Yes, sorry I have not done a good job at maintaining this repo. You can provide a vector of length N where N is the number of observations in the dataset as the second argument to the `DiffusionMap` constructor. This library does not compute the weights as discussed in the paper you cited. However, if you calculate the weights using umbrella sampling, you can provide them to the library and you should be good to go. 

Hope this helps!

**Comment by yihengwuKP** [comment]
Hi Hythem, many thanks for your quick reply, this helps a lot! I'll try that! Is your implementation about the reweighting in any of the three citations you provided? Thanks!

**Comment by hsidky** [comment]
It's actually a generic implementation allowing you to provide an arbitrary weight for an observation. If you perform umbrella sampling as described in the paper you cited, you could compute weights for each configuration and use it in this implementation. Alternatively, you can do things as outlined in the paper and it still can be used with this library,

**Comment by yihengwuKP** [comment]
Thanks for your detailed explanation! Btw thanks for sharing your implementation of diffusion map, it's really helpful and saved me a lot of time!
